name: Smoke Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - circle-socket-2

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "host-x64-target-arm",
              runs-on: docker,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib:20-custom-v2",
              prefix: "arm-none-eabi-",
              circle-machine: "1",
              qemu-bin: "qemu-system-arm",
              qemu-machine: "raspi0",
              qemu-kernel-opt: "-bios",
              qemu-img: "kernel.img"
            }
          - {
              name: "host-x64-target-aarch64",
              runs-on: docker,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib:20-custom-v2",
              prefix: "aarch64-none-elf-",
              circle-machine: "3",
              qemu-bin: "qemu-system-aarch64",
              qemu-machine: "raspi3b",
              qemu-kernel-opt: "-kernel",
              qemu-img: "kernel8.img"
            }
          - {
              name: "host-aarch64-target-arm",
              runs-on: ubuntu-arm-22.04,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib-arm:20-custom-v1",
              prefix: "arm-none-eabi-",
              circle-machine: "1",
              qemu-bin: "qemu-system-arm",
              qemu-machine: "raspi0",
              qemu-kernel-opt: "-bios",
              qemu-img: "kernel.img"
            }
          - {
              name: "host-aarch64-target-aarch64",
              runs-on: ubuntu-arm-22.04,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib-arm:20-custom-v1",
              prefix: "aarch64-none-elf-",
              circle-machine: "3",
              qemu-bin: "qemu-system-aarch64",
              qemu-machine: "raspi3b",
              qemu-kernel-opt: "-kernel",
              qemu-img: "kernel8.img"
            }

    name: ${{ matrix.config.name }}

    runs-on: ${{ matrix.config.runs-on }}

    container:
      image: ${{ matrix.config.container }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure circle-stdlib with QEMU support
        run: |
          ./configure -p ${{ matrix.config.prefix }} -r ${{ matrix.config.circle-machine }} --qemu

      - name: Build libraries
        run: make -j$(nproc)

      - name: Build samples
        run: make build-samples

      - name: Run smoke test with QEMU
        run: |
          cd samples/05-smoketest
          # Extract blank SD card image
          ../../testdata/setup-sd.sh
          # Guard against endless loop in QEMU run (120 CPU secs)
          ulimit -t 120
          ${{ matrix.config.qemu-bin }} -M ${{ matrix.config.qemu-machine }} ${{ matrix.config.qemu-kernel-opt }} ${{ matrix.config.qemu-img }} -display none -nographic -semihosting -sd sdcard.img

      - name: Run basic socket test
        run: |
          cd tests/01-basic-socket
          CFG_QEMU_BIN=${{ matrix.config.qemu-bin }} \
          CFG_QEMU_MACHINE=${{ matrix.config.qemu-machine }} \
          CFG_QEMU_OPT=${{ matrix.config.qemu-kernel-opt }} \
          CFG_QEMU_IMG=${{ matrix.config.qemu-img }} \
          bash -x ./run_test.sh
