name: Smoke Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        kasan:
          - {
              name: "Without Address Sanitizer",
              kasan_opt: ""
            }
          - {
              name: "With Address Sanitizer",
              kasan_opt: "--kasan"
            }

        config:
          - {
              name: "host-x64-target-arm",
              runs-on: docker,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib:20-custom-v3",
              prefix: "arm-none-eabi-",
              circle-machine: "1",
              qemu-bin: "qemu-system-arm",
              qemu-machine: "raspi0",
              qemu-kernel-opt: "-bios",
              qemu-img: "kernel.img",
            }
          - {
              name: "host-x64-target-aarch64",
              runs-on: docker,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib:20-custom-v3",
              prefix: "aarch64-none-elf-",
              circle-machine: "3",
              qemu-bin: "qemu-system-aarch64",
              qemu-machine: "raspi3b",
              qemu-kernel-opt: "-kernel",
              qemu-img: "kernel8.img",
            }
          - {
              name: "host-aarch64-target-arm",
              runs-on: ubuntu-arm-22.04,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib-arm:20-custom-v2",
              prefix: "arm-none-eabi-",
              circle-machine: "1",
              qemu-bin: "qemu-system-arm",
              qemu-machine: "raspi0",
              qemu-kernel-opt: "-bios",
              qemu-img: "kernel.img",
            }
          - {
              name: "host-aarch64-target-aarch64",
              runs-on: ubuntu-arm-22.04,
              container: "codeberg.org/larchcone/ci/node-circle-stdlib-arm:20-custom-v2",
              prefix: "aarch64-none-elf-",
              circle-machine: "3",
              qemu-bin: "qemu-system-aarch64",
              qemu-machine: "raspi3b",
              qemu-kernel-opt: "-kernel",
              qemu-img: "kernel8.img",
            }
  
    name: ${{ matrix.config.name }} - ${{ matrix.kasan.name }}

    # Exclude configurations that fail for unknown reasons with KASAN enabled.
    # These do not report an actual Address Sanitizer errr, but do not
    # actually start because of QEMU error messages:
    # localhost [127.0.0.1] 5000 (?) open
    # qemu-system-aarch64: Slirp: Failed to send packet, ret: -
    # if: ${{ matrix.kasan.name == 'Without Address Sanitizer' }}

    runs-on: ${{ matrix.config.runs-on }}

    container:
      image: ${{ matrix.config.container }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment variables from matrix
        run: |
          echo "CFG_QEMU_BIN=${{ matrix.config.qemu-bin }}" >> $GITHUB_ENV
          echo "CFG_QEMU_MACHINE=${{ matrix.config.qemu-machine }}" >> $GITHUB_ENV
          echo "CFG_QEMU_OPT=${{ matrix.config.qemu-kernel-opt }}" >> $GITHUB_ENV
          echo "CFG_QEMU_IMG=${{ matrix.config.qemu-img }}" >> $GITHUB_ENV

      - name: Configure circle-stdlib with QEMU support
        run: |
          ./configure -p ${{ matrix.config.prefix }} -r ${{ matrix.config.circle-machine }} --qemu ${{ matrix.kasan.kasan_opt }}

      - name: Build libraries
        run: make -j$(nproc)

      - name: Build samples
        run: make build-samples

      - name: Run smoke test with QEMU
        run: |
          cd samples/05-smoketest
          # Extract blank SD card image
          ../../testdata/setup-sd.sh
          # Guard against endless loop in QEMU run (120 CPU secs)
          ulimit -t 120
          ${{ matrix.config.qemu-bin }} -M ${{ matrix.config.qemu-machine }} ${{ matrix.config.qemu-kernel-opt }} ${{ matrix.config.qemu-img }} -display none -nographic -semihosting -sd sdcard.img

      - name: Build test library
        run: |
          make -C tests/lib

      - name: Run basic socket test
        if: ${{ matrix.kasan.name == 'Without Address Sanitizer' }}
        run: |
          cd tests/01-basic-socket
          ./run_test.sh

      - name: Run basic select/poll socket test
        run: |
          cd tests/02-basic-socket-mux
          ./run_test.sh
